package jenkins.python.expoint;


import hudson.DescriptorExtensionList;
import hudson.Extension;
import hudson.ExtensionPoint;
import hudson.model.Describable;
import hudson.model.Descriptor;
import hudson.model.Descriptor.FormException;
import jenkins.model.Jenkins;
import hudson.model.Item;
import hudson.model.ItemGroup;
import hudson.model.ListView;
import hudson.model.View;
import hudson.util.DescriptorList;
import org.kohsuke.stapler.export.Exported;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import hudson.views.*;
import hudson.views.ListViewColumn.*;
import jenkins.python.DataConvertor;
import jenkins.python.PythonExecutor;

/**
 * This class was automatically generated by the PWM tool on 2014/03/21.
 * @see hudson.views.ListViewColumn
 */
public abstract class ListViewColumnPW extends ListViewColumn {
	private transient PythonExecutor pexec;

	private void initPython() {
		if (pexec == null) {
			pexec = new PythonExecutor(this);
			String[] jMethods = new String[0];
			String[] pFuncs = new String[0];
			Class[][] argTypes = new Class[0][];
			pexec.checkAbstrMethods(jMethods, pFuncs, argTypes);
			String[] functions = new String[3];
			functions[0] = "get_column_caption";
			functions[1] = "shown_by_default";
			functions[2] = "get_descriptor";
			int[] argsCount = new int[3];
			argsCount[0] = 0;
			argsCount[1] = 0;
			argsCount[2] = 0;
			pexec.registerFunctions(functions, argsCount);
		}
	}

	@Override
	@Exported
	public String getColumnCaption() {
		initPython();
		if (pexec.isImplemented(0)) {
			return (String) pexec.execPython("get_column_caption");
		} else {
			return super.getColumnCaption();
		}
	}

	@Override
	public boolean shownByDefault() {
		initPython();
		if (pexec.isImplemented(1)) {
			return pexec.execPythonBool("shown_by_default");
		} else {
			return super.shownByDefault();
		}
	}

	@Override
	public Descriptor<ListViewColumn> getDescriptor() {
		initPython();
		if (pexec.isImplemented(2)) {
			return (Descriptor) pexec.execPython("get_descriptor");
		} else {
			return super.getDescriptor();
		}
	}

	public String superGetColumnCaption() {
		return super.getColumnCaption();
	}

	public boolean superShownByDefault() {
		return super.shownByDefault();
	}

	public Descriptor<ListViewColumn> superGetDescriptor() {
		return super.getDescriptor();
	}

	public Object execPython(String function, Object... params) {
		initPython();
		return pexec.execPython(function, params);
	}

	public byte execPythonByte(String function, Object... params) {
		initPython();
		return pexec.execPythonByte(function, params);
	}

	public short execPythonShort(String function, Object... params) {
		initPython();
		return pexec.execPythonShort(function, params);
	}

	public char execPythonChar(String function, Object... params) {
		initPython();
		return pexec.execPythonChar(function, params);
	}

	public int execPythonInt(String function, Object... params) {
		initPython();
		return pexec.execPythonInt(function, params);
	}

	public long execPythonLong(String function, Object... params) {
		initPython();
		return pexec.execPythonLong(function, params);
	}

	public float execPythonFloat(String function, Object... params) {
		initPython();
		return pexec.execPythonFloat(function, params);
	}

	public double execPythonDouble(String function, Object... params) {
		initPython();
		return pexec.execPythonDouble(function, params);
	}

	public boolean execPythonBool(String function, Object... params) {
		initPython();
		return pexec.execPythonBool(function, params);
	}

	public void execPythonVoid(String function, Object... params) {
		initPython();
		pexec.execPythonVoid(function, params);
	}
}
