package jenkins.python.expoint;


import hudson.DescriptorExtensionList;
import hudson.ExtensionPoint;
import hudson.model.Describable;
import jenkins.model.Jenkins;
import hudson.tools.*;
import hudson.tools.ToolProperty.*;
import jenkins.python.DataConvertor;
import jenkins.python.PythonExecutor;

/**
 * This class was automatically generated by the PWM tool on 2014/03/21.
 * @see hudson.tools.ToolProperty
 */
public abstract class ToolPropertyPW<T extends ToolInstallation> extends ToolProperty<T> {
	private transient PythonExecutor pexec;

	private void initPython() {
		if (pexec == null) {
			pexec = new PythonExecutor(this);
			String[] jMethods = new String[1];
			jMethods[0] = "type";
			String[] pFuncs = new String[1];
			pFuncs[0] = "type";
			Class[][] argTypes = new Class[1][];
			argTypes[0] = new Class[0];
			pexec.checkAbstrMethods(jMethods, pFuncs, argTypes);
			String[] functions = new String[2];
			functions[0] = "set_tool";
			functions[1] = "get_descriptor";
			int[] argsCount = new int[2];
			argsCount[0] = 1;
			argsCount[1] = 0;
			pexec.registerFunctions(functions, argsCount);
		}
	}

	@Override
	public Class<T> type() {
		initPython();
		return (Class) pexec.execPython("type");
	}

	@Override
	public void setTool(T tool) {
		initPython();
		if (pexec.isImplemented(0)) {
			pexec.execPythonVoid("set_tool", tool);
		} else {
			super.setTool(tool);
		}
	}

	@Override
	public ToolPropertyDescriptor getDescriptor() {
		initPython();
		if (pexec.isImplemented(1)) {
			return (ToolPropertyDescriptor) pexec.execPython("get_descriptor");
		} else {
			return super.getDescriptor();
		}
	}

	public void superSetTool(T tool) {
		super.setTool(tool);
	}

	public ToolPropertyDescriptor superGetDescriptor() {
		return super.getDescriptor();
	}

	public Object execPython(String function, Object... params) {
		initPython();
		return pexec.execPython(function, params);
	}

	public byte execPythonByte(String function, Object... params) {
		initPython();
		return pexec.execPythonByte(function, params);
	}

	public short execPythonShort(String function, Object... params) {
		initPython();
		return pexec.execPythonShort(function, params);
	}

	public char execPythonChar(String function, Object... params) {
		initPython();
		return pexec.execPythonChar(function, params);
	}

	public int execPythonInt(String function, Object... params) {
		initPython();
		return pexec.execPythonInt(function, params);
	}

	public long execPythonLong(String function, Object... params) {
		initPython();
		return pexec.execPythonLong(function, params);
	}

	public float execPythonFloat(String function, Object... params) {
		initPython();
		return pexec.execPythonFloat(function, params);
	}

	public double execPythonDouble(String function, Object... params) {
		initPython();
		return pexec.execPythonDouble(function, params);
	}

	public boolean execPythonBool(String function, Object... params) {
		initPython();
		return pexec.execPythonBool(function, params);
	}

	public void execPythonVoid(String function, Object... params) {
		initPython();
		pexec.execPythonVoid(function, params);
	}
}
